### ISSUE TITLE
Getting a user does not work

### ISSUE THREAD

**Issue by Faldrian** [marekjm/diaspy#10]
Hi!

I used code from your unit_test to have a working example of how to use diaspy.

I tried this:

``` python
contacts = diaspy.people.Contacts(con)
result = contacts.get()
print(result)
for i in result:
    print(i)
```

But it complains:

```
Traceback (most recent call last):
  File "./di.py", line 19, in <module>
    print(result)
  File "/usr/lib64/python3.3/site-packages/diaspy-0.3.1-py3.3.egg/diaspy/people.py", line 60, in __repr__
  File "/usr/lib64/python3.3/site-packages/diaspy-0.3.1-py3.3.egg/diaspy/people.py", line 54, in __getitem__
KeyError: 'diaspora_name'
```

Where is "diaspora_name" set?

**Comment by marekjm** [comment]
@Faldrian Hi. You should be able to fetch people. Could you check if the fix works for you?

**Comment by Faldrian** [comment]
It's long since I had used this project... I proably won't check if it works, since I don't do anything with it at the moment. But thanks for cleaning up. :)

**Comment by marekjm** [comment]
Sure ;-) It's been more than 3 years so I guess that's to be expected. Have a nice weekend then!
