### ISSUE TITLE
"could not find valid CSRF token" error at creating Connection instance.

### ISSUE THREAD

**Issue by cnngimenez** [marekjm/diaspy#18]
Hi!

When creating a new Connection instance, the `_fetchtoken()` method tries to retrieve the CSRF token. According to the RegExp (`_token_regex` variable), it tries to match first the `csrf-token` value, then look for the `content` attribute, but now, at joindiaspora.com the HTML code have this:

    <meta content="... CSRF TOKEN HERE ..." name="csrf-token" />

This means that it would never find it.

I changed the `Connection._token_regex` as follow and now seems to work:

        _token_regex = re.compile(r'(name="csrf-token"\s+content="(.*?)|content="(.*?)"\s+name="csrf-token")')

Maybe you can add this so diaspy can work.

Cheers! :smiley:

**Comment by cnngimenez** [comment]
Oh! I was mistaken! It wasn't the regexp!... 

I found there is two regexp for checking in both order, but the results of the second is never stored into the `token` local variable. 

I'll give you the patch that really works:

```patch
diff --git a/diaspy/connection.py b/diaspy/connection.py
index 4a2a6e9..3a6830d 100644
--- a/diaspy/connection.py
+++ b/diaspy/connection.py
@@ -184,7 +184,7 @@ class Connection():
         """
         request = self.get('stream')
         token = self._token_regex.search(request.text)
-        if token is None: self._token_regex_2.search(request.text)
+        if token is None: token = self._token_regex_2.search(request.text)
         if token is not None: token = token.group(1)
         else: raise errors.TokenError('could not find valid CSRF token')
         self._token = token
```

Sorry for the mess :confused:  :smile:

**Comment by marekjm** [comment]
Thank you for the patch! I will release a hotfix version with it.

**Comment by marekjm** [comment]
Here you can download the fixed release: https://github.com/marekjm/diaspy/releases/tag/v0.5.0.1

**Comment by cnngimenez** [comment]
:+1: Thanks! :smile:
