### ISSUE TITLE
Cannot retrieve __repr__() on Notification instance

### ISSUE THREAD

**Issue by cnngimenez** [marekjm/diaspy#19]
I want to retrieve notifications, so I use this commands:

``` python
>>> c = Connection("https://mypod.org", "myusername", "mypassword")
>>> c.login()
******************************** (CSRF TOKEN RETRIEVED HERE :smile: )
>>> n = Notifications(c)
>>> n.last()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/diaspy-0.4.3-py3.4.egg/diaspy/models.py", line 179, in __repr__
  File "/usr/lib/python3.4/site-packages/diaspy-0.4.3-py3.4.egg/diaspy/models.py", line 198, in when
AttributeError: 'NoneType' object has no attribute 'group'
>>> l = n.last()
>>> str(l[0])
"THE NOTIFICATION MESSAGE SHOWS CORRECTLY :smile: "
```

I think that the `Notification.when()` method doesn't check if the regexp found something or not, and what to do if nothing has been founded... Or maybe the "note_html" field changed at the notification JSON?
Remember that I'm in another country, maybe is the time internationalization, and there is a "created_at" JSON field with a standard (ISO standard?) date.

Cheers!

**Comment by marekjm** [comment]
I'll look into that, but don't expect a patch to be ready sooner then by the end on the weekend. Thanks for opening teh issue.

**Comment by cnngimenez** [comment]
Hey! I have created a fork, and I'll try to help whenever I can.

I have just sended you [a pull-request](https://github.com/marekjm/diaspy/pull/20) for closing this issue (if the solution is right for you).

:+1:
Cheers!

**Comment by Flashwalker** [comment]
Still fails.

**Comment by marekjm** [comment]
@Flashwalker Care to look at it? I'd welcome a patch if you offered a solution.

If you're not interested in producing a patch, provide a stack trace Python gives you, a more detailed description of the problem, and how to trigger it. Enigmatic "Still fails." is not really helpful.

**Comment by Flashwalker** [comment]
My traceback looks the same as at the start of the topic:
```
>>> n = diaspy.notifications.Notifications(c)
>>> notifs = n.last()
>>> notifs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/diaspy/models.py", line 179, in __repr__
    return '{0}: {1}'.format(self.when(), str(self))
  File "/usr/local/lib/python3.4/dist-packages/diaspy/models.py", line 198, in when
    return self._when_regexp.search(self._data['note_html']).group(0)
AttributeError: 'NoneType' object has no attribute 'group'
>>> for i in notifs:
...     str(i)
**NOTIFICATION MESSAGE SHOWS CORRECTLY**
```
