### ISSUE TITLE
Aspect._getAjax returns 404

### ISSUE THREAD

**Issue by jaywink** [marekjm/diaspy#21]
For diasp.eu, which runs 0.5.1.1, retrieving users from an aspect doesn't seem to work, hitting a 404 in the `Aspect._getAjax`, probably due to refactoring done to the aspects in 0.5..

Hopefully we'll have that API soon :D But logging this here just for completeness. Came up in https://github.com/jaywink/diaspora-tools/issues/2

**Comment by marekjm** [comment]
Hopefully! I am waiting for that moment to come!

I'll look into this during the weekend, thanks for opening the issue.

**Comment by marekjm** [comment]
Fixed in 03d983fea58c4cb5b1a00edf1adf85be346da54c.
