### ISSUE TITLE
Photo upload error message "Extra data"

### ISSUE THREAD

**Issue by jpope777** [marekjm/diaspy#22]
I'm suddenly unable to upload images with diaspy whereas I previously was able to.

An example of the script I've been using:

```
#!/usr/bin/python

import diaspy
message = open("/tmp/message.md", "r")
d = diaspy.connection.Connection(pod='https://pod.jpope.org',
                                 username='jpope',
                                 password='thisismypassword')
d.login()
stream = diaspy.streams.Stream(d)
id = stream._photoupload(filename='/tmp/test.png')
stream.post(photos=id,text=message.read())
```

Is returning this traceback:

```
Traceback (most recent call last):
  File "/home/jpope/bin/diaspost", line 10, in <module>
    id = stream._photoupload(filename='/tmp/test.png')
  File "/usr/lib/python3.4/site-packages/diaspy-0.4.3-py3.4.egg/diaspy/streams.py", line 284, in _photoupload
  File "/usr/lib/python3.4/site-packages/diaspy-0.4.3-py3.4.egg/diaspy/connection.py", line 226, in getUserData
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 346, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 1157 - line 1 column 1238 (char 1156 - 1237)
```

This is on a fully up to date Arch system.

**Comment by marekjm** [comment]
Thanks for the info. I'll look into this and see if I can do something about it.

**Comment by balasankarc** [comment]
I had this issue and IIRC diaspy doesn't support uploading photos from other paths than current directory. When I changed directory to the one where photo resides and then gave "./<filename>" as filename argument, it worked. 
Will confirm it and tell.

**Comment by marekjm** [comment]
For future reference: this "extra data" error appears when Diaspora\* rejects CSRF tokens sent by Diaspy.
I don't know why it does it. If somebody wants to fix the issue and send me a patch - feel free to.

**Comment by kianby** [comment]
There is an additional info named *gon.appConfig* in HTTP response for an image posting.  

Sample anonymized data:

    {
      "id":7355,
      "guid":"56896070991321973302a00053625",
      "name":"Bill",
      "diaspora_id":"bill@diaspora.org",
      "avatar":{
        "small":"https://diaspora.org/uploads/images/thumb_small_738337383330e.jpg",
        "medium":"https://diaspora.org/uploads/images/thumb_medium_738337383330e.jpg",
        "large":"https://diaspora.org/uploads/images/thumb_large_738337383330e.jpg"},
        "notifications_count":0,
        "unread_messages_count":0,
        "admin":false,
        "moderator":false,
        "aspects":[
          {"id":4156,"name":"Famille","selected":true},
          {"id":4156,"name":"Amis","selected":true},
          {"id":4156,"name":"Travail","selected":true},
          {"id":4156,"name":"Connaissances","selected":true}
        ],
        "services":[],
        "following_count":59,
        "configured_services":[]};gon.appConfig={"chat":{"enabled":false},"settings":{"podname":"Somewhere*"},"map":{"mapbox":{"enabled":false,"access_token":null,"style":"mapbox/streets-v9"}}}

Proposed patch for **connection.py**:

    --- a/diaspy/connection.py
    +++ b/diaspy/connection.py
    @@ -24,7 +24,7 @@ class Connection():
         _userinfo_regex = re.compile(r'window.current_user_attributes = ({.*})')
         # this is for older version of D*
         _token_regex_2 = re.compile(r'content="(.*?)"\s+name="csrf-token')
    -    _userinfo_regex_2 = re.compile(r'gon.user=({.*});gon.preloads')
    +    _userinfo_regex_2 = re.compile(r'gon.user=({.*?});gon.')
         _verify_SSL = True
    
         def __init__(self, pod, username, password, schema='https'):
    @

**Comment by marekjm** [comment]
Nice catch! Care to submit a pull request?

**Comment by kianby** [comment]
Done :-) I like **diaspy** and I have based [mail2diaspora](https://github.com/kianby/mail2diaspora) on it
