### ISSUE TITLE
0.3.0 is on pypi?

### ISSUE THREAD

**Issue by pjz** [marekjm/diaspy#24]
Can you get pypi project ownership from the old maintainer?  If not, would you consider renaming? I'd really like to be able to 'pip install diaspy' instead of having to clone it, build it, and manually ship around eggs or wheels or whatever.

**Comment by marekjm** [comment]
Diaspy should be installable from PyPI now: https://pypi.python.org/pypi/diaspy-api/

**Comment by Flashwalker** [comment]
pypi.python.org shows version 0.5.1, but `pip3 search` says 0.3.0:
```
$ pip3 search diaspy
diaspy-api                - Unofficial Python API for Diaspora*
diaspy                    - A Python API to the social network Diaspora*
  INSTALLED: 0.4.3
  LATEST:    0.3.0
```

**Comment by Flashwalker** [comment]
pypi.python.org shows version 0.5.1, but here we have 0.4.2, right?
Is there devel version?

**Comment by marekjm** [comment]
> pypi.python.org shows version 0.5.1, but here we have 0.4.2, right?

Nope, if you look at https://github.com/marekjm/diaspy/releases the latest version is 0.5.1.

>  Is it a devel version on pypi?

*All* versions of Diaspy are "devel".
