### ISSUE TITLE
Unicode Support

### ISSUE THREAD

**Issue by balasankarc** [marekjm/diaspy#25]
Hi,
When I try to post unicode text, it raises errors. Even if I try to decode it and post, same error.

\>>> a
'\xe0\xb4\xac\xe0\xb4\xbe\xe0\xb4\xb2\xe0\xb5\x81'
\>>> b = a.decode('utf-8')
\>>> b
u'\u0d2c\u0d3e\u0d32\u0d41'
\>>> stream.post(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/diaspy/models.py", line 345, in __repr__
    return '{0} ({1}): {2}'.format(self._data['author']['name'], self._data['author']['guid'], self._data['text'])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-21: ordinal not in range(128)
\>>> stream.post(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/diaspy/models.py", line 345, in __repr__
    return '{0} ({1}): {2}'.format(self._data['author']['name'], self._data['author']['guid'], self._data['text'])
UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-21: ordinal not in range(128)

Any help on solving it will be appreciated. Thanks

**Comment by marekjm** [comment]
From the listing you've posted I see that you're running Python 2.7. The library, however, is developed for Python 3. Is there anything stopping you from switching to the new Python?

**Comment by balasankarc** [comment]
It was an issue with the encoding. Fixed with Python 2.7 itself. Thanks for your help.
