### ISSUE TITLE
Can't post because of error in stream

### ISSUE THREAD

**Issue by gjedeer** [marekjm/diaspy#27]
My code goes like this:

```
    c.login()
    stream = diaspy.streams.Stream(c)
    stream.post(markdown)

```

so I'm not really interested in contents of the stream. However, one of the posts in stream returns 404 and an exception is thrown, prohibiting me from posting.

```
    stream = diaspy.streams.Stream(c)
  File "/app/venv/src/diaspy/diaspy/streams.py", line 34, in __init__
    if fetch: self.fill()
  File "/app/venv/src/diaspy/diaspy/streams.py", line 122, in fill
    self._stream = self._obtain()
  File "/app/venv/src/diaspy/diaspy/streams.py", line 66, in _obtain
    return [Post(self._connection, guid=post['guid']) for post in request.json()]
  File "/app/venv/src/diaspy/diaspy/models.py", line 337, in __init__
    if fetch: self._fetchdata()
  File "/app/venv/src/diaspy/diaspy/models.py", line 369, in _fetchdata
    raise errors.PostError('{0}: could not fetch data for post: {1}'.format(request.status_code, id))
PostError: 404: could not fetch data for post: 0d85510a4f24ad0df151caf1a3db579******@friendicared.de
```

I've worked around it like this, not sure it's an acceptable solution but it works for me:

```
--- streams.py  2015-10-03 19:28:43.364444537 +0200
+++ /app/venv/src/diaspy/diaspy/streams.py       2015-10-03 19:23:33.932285274 +0200
@@ -63,7 +63,12 @@
         request = self._connection.get(self._location, params=params)
         if request.status_code != 200:
             raise errors.StreamError('wrong status code: {0}'.format(request.status_code))
-        return [Post(self._connection, guid=post['guid']) for post in request.json()]
+        posts = []
+        for post in request.json():
+            try:
+                posts.append(Post(self._connection, guid=post['guid']))
+            except errors.PostError:
+                pass
 
     def _expand(self, new_stream):
         """Appends older posts to stream.
```

**Comment by marekjm** [comment]
Looks good for me. I will merge it with one small adjustment: it will be configurable whether to `pass` or reraise the exception. Since it looks like passing is the desirable safe default (as your case suggests) it will stay that way.

PS. Thanks for the patch.

**Comment by jpope777** [comment]
This looks like a suitable workaround for issue #23 as well...

**Comment by chaica** [comment]
Hi,

As indicated by the last reference, I'm blocked using feedDiasp by this bug. Would it be possible to apply the correct patch as stated by @marekjm on the source code? 

The patch from @gjedeer works just fine. I hacked my local diaspy installation waiting for the upstream fix. 

Regards,
Carl

**Comment by marekjm** [comment]
Should be fixed by a commit on devel branch. By default `PostError` exceptions are suppressed.

**Comment by marekjm** [comment]
As an alternative, try instantiating `Stream` with `fetch` parameter set to `False`. This will prevent `Stream` from fetching posts.
