### ISSUE TITLE
Storing Connection issue

### ISSUE THREAD

**Issue by Flashwalker** [marekjm/diaspy#29]
I'm trying to store and reuse `Connection` object via pickle.

The problem is, that it's not storing completely.
Storing and loading of object works, but i get `_login_data` is empty `{}`

How to get it works?

Notice: Found, that in my case the pickle is storing with protocol 2 (even if i set it to 3)

**Comment by marekjm** [comment]
Why store `Connection` objects if you can just store credentials and just reconnect? I don't see a point in this.

If you care about pickling `Connection` objects I'd welcome a patch, but I will not take time to look into it myself.

**Comment by Flashwalker** [comment]
Well, actually i want to post a lot of data. 
And, I think it would be not very good to get all those auth requests/tokens each time for each post frequently. 
I made workaround with manually filling `_login_data` dict, and now reusing (as i think) connection, but...
What i want, is like i do it via *curl*. Get access token and authenticity token and no need username/password auth each time for each post. Just spam with no extra connections.
And looks like the same can't be done via *diaspy*, yep?

**Comment by marekjm** [comment]
Diaspy does not operate on "access token" of any kind, because D\* does not provide such functionality. The token you're talking about is extracted from the HTML received after logging in, and is then subsequently used to imitate requests sent by the browser UI. So while it *might* look like you're using a "token"... you're not.

**Comment by Flashwalker** [comment]
Feels like running faster.

**Comment by marekjm** [comment]
@Flashwalker I'm closing this with a "wontfix" but if you find someone who can code this for you (or point me to information *how to* get access token and authenticity token for D\*) feel free to reopen the issue and we can look at it again.

**Comment by Flashwalker** [comment]
Hi, here i was found how to get tokens:
https://pod.jpope.org/posts/1da068b01d2b01336bd10e5b4d50b4e6
https://kentshikama.com/posts/68f70c801c0d0133da7b04015765ae01

And i made some actualization and wrote bash script (based on jpope's removed podwrapper script):
https://notabug.org/uzver/diclish

Script collects tokens consistently in REGISTER and TOKENS functions and checks auth in VALIDTOKEN function (you want lines with `curl` and `awk`).  
(Don't pay attention to commented scrap).

**Comment by Flashwalker** [comment]
I forgot, i have a flow how to get tokens. Just edit pod and password in first line and run with code for curl or for httpie in bash:
http://sprunge.us/IPFS?bash

**Comment by marekjm** [comment]
Thanks. I'm sure a new maintainer will find the links handy :-)
