### ISSUE TITLE
Does not work with diasp.org

### ISSUE THREAD

**Issue by gjedeer** [marekjm/diaspy#30]
```
_token_regex = re.compile(r'content="(.*?)"\s+name="csrf-token')
```
while the code on the site has opposite order:
```
<meta name="csrf-token" content="3k26wPHLIwYhG68U1tdiAttixmhyuIcZSXE9s1y4TXWDHYwrli3Sj3TcagcplnJwIp9FTRRI+IQMPBw==" />
```

Possible fixes:
* create a 2nd token regex and match it as a fallback when the main one fails
* use BeautifulSoup
* match whole tags containing "csrf-token" with a regex, then find content in these tags

**Comment by marekjm** [comment]
Diaspy should work with both versions. The token-extracting code includes a second (fallback) regex.

See here: https://github.com/marekjm/diaspy/blob/master/diaspy/connection.py#L25
