### ISSUE TITLE
new maintainer

### ISSUE THREAD

**Issue by lumy** [marekjm/diaspy#32]
Hey,

I'm really interested into becoming the new maintainer, I'm doing python since few years now and i use diaspora since a few but i love it :)
But i guess i wasn't the first one to tell you that, so i think i should have a look at the code, Can i contact you if i have any question ?.

Thanks anyway for your time :)
Best Regards.

Timothee - Lumy - Menage

**Comment by marekjm** [comment]
Sure thing :-) Ask away if you have any questions.

**Comment by CYBERDEViLNL** [comment]
@lumy, if you are still interested in helping developing diaspy that will be great but I close this issue for now. Like @marekjm said if there are questions then ask away :-)
