### ISSUE TITLE
more() function

### ISSUE THREAD

**Issue by CYBERDEViLNL** [marekjm/diaspy#36]
Hello,

I'm trying to use the more() function but I'm not getting the desired result.
It just prints the same list again. Am I doing something wrong?

```
def print_posts(stream):
	print(len(stream))
	for post in stream:
		print("\t{}".format(post.guid))
		
connection = diaspy.connection.Connection(login_details['pod'], username=login_details['username'], password=login_details['password'])
connection.login()

stream = diaspy.streams.Stream(connection)
print_posts(stream)

print("\nmore")
stream.more()
print_posts(stream)
```

**Comment by CYBERDEViLNL** [comment]
I have found the problem. The problem is that post **ids** are all set to 0 while the functions _expand() and _update() rely on that they are unique. Maybe update to **guids** like this?

```
    def _expand(self, new_stream):
        """Appends older posts to stream.
        """
        guids = [post.guid for post in self._stream]
        
        stream = self._stream
        for post in new_stream:
            if post.guid not in guids:
                stream.append(post)
                guids.append(post.guid)
        self._stream = stream
```

**Comment by marekjm** [comment]
Hi @CYBERDEViLNL !

Thank you for the bug report. If you would be willing to submit a pull request fixing this bug I'd be more than happy to review and merge it :-)

**Comment by CYBERDEViLNL** [comment]
Ok great. Like your code btw :-)
