### ISSUE TITLE
Push 0.6.0 to PyPI

### ISSUE THREAD

**Issue by Lynnesbian** [marekjm/diaspy#45]
The latest version of diaspy is [0.6.0](https://github.com/marekjm/diaspy/releases/tag/v0.6.0), but the version PyPI is [0.5.1](https://pypi.org/project/diaspy-api/). Would it be possible to push the new version to PyPI?

Thanks in advance

**Comment by CYBERDEViLNL** [comment]
@marekjm can you look into this since you are the package maintainer at pypi?

**Comment by marekjm** [comment]
Sure. Do you have an account on PyPI? I would gladly add you as a maintainer or just transfer the ownership of the project to you.

**Comment by CYBERDEViLNL** [comment]
Ok that would be great :-) , I just made one https://pypi.org/user/CYBERDEViLNL/

**Comment by marekjm** [comment]
Done. You're now an owner of the project on PyPI. Congratulations! :-)

**Comment by CYBERDEViLNL** [comment]
Thank you :-) Can you also add me to TestPyPi? Since this would be my first package on PyPi i'd like to test.

**Comment by marekjm** [comment]
Done. I completely forgot about that one ;-)

**Comment by CYBERDEViLNL** [comment]
Great :-)

**Comment by CYBERDEViLNL** [comment]
@Lynnesbian package is updated ;-)
